# fly.toml app configuration file generated for init-contact-info on 2024-01-25T09:43:14-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "init-contact-info"
primary_region = "bog"

[build]

[http_service]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
