# fly.toml app configuration file generated for init-contact-info-v1 on 2024-03-13T11:01:37-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'init-contact-info-v1'
primary_region = 'bog'

[build]

[http_service]
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
