---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-contact-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init-contact-info
  template:
    metadata:
      labels:
        app: init-contact-info
    spec:
      containers:
        - name: init-contact-info
          image: docker.io/jamp1992/init-contact-info:v2
          env:
            - name: CLIENT_TX_INIT_SEARCH_START_URL
              value: http://bd-transaction:80/api/v1/invexdijin
            - name: CLIENT_SEND_EMAIL_CONTACT_URL
              value: http://email-notification:80/api/v1/invexdijin/contact-form
            - name: CLIENT_API1_SEARCH_PEOPLE_URL
              value: http://a4b01e34-5c72-451f-a49e-c2314085c2c2.mock.pstmn.io/police
            - name: CLIENT_API1_TOKEN_KEY
              value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRJZCI6IjY0NTkwMzM0MWYzMTBiZGY4ZTU4NGI0ZCIsInYiOjIsInJvbGUiOiJjbGllbnQiLCJKV1RQaHJhc2UiOiI2NDU5MDMzMjIyNGU0MmRmYjA2NzlmZGUiLCJleHBpcmVzQXQiOiIyMDI0LTAxLTE4IDIwOjE4OjU5IiwiaWF0IjoxNzAzMDE3MTM5fQ.17hmEm09DV3j15sXalSxkDs8g4KftnoVcDwvRVz0ai8
          readinessProbe:
            failureThreshold: 10
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            httpGet:
              httpHeaders:
                - name: Accept
                  value: application/json
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
#          imagePullPolicy: Always
#          ports:
#            - containerPort: 8080
#              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: init-contact-info
spec:
  type: ClusterIP
  selector:
    app: init-contact-info
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: init-contact-info-external
spec:
  type: LoadBalancer
  selector:
    app: init-contact-info
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080